### ISSUE TITLE
Game freezes while undoing death by monster

### ISSUE THREAD

**Issue by TheJakeSchmidt** [eevee/lexys-labyrinth#10] opened 2020-12-12 23:24 UTC
In the current version of Lexy's Labyrinth, I can undo from a death by e.g. fire like normal, but not from a death by monster. When I hold down Z, it undoes the death but nothing else (the clock counts up), and when I let go of Z it's frozen on the death frame with the clock counting down.

I can reproduce on a Pixelbook, and also Chrome on Windows 10.

**Comment by TheJakeSchmidt** [comment] 2020-12-13 00:28
Oh, and I should mention, it prints this to the console at the time of the freeze:

```
tileset.js:1258 fireball Tile {type: {…}, direction: "north", cell: Cell(3), slide_mode: null, movement_cooldown: 4, …}
draw_type @ tileset.js:1258
draw @ tileset.js:893
draw @ renderer-canvas.js:178
_redraw @ main.js:1153
redraw @ main.js:1137
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
requestAnimationFrame (async)
redraw @ main.js:1143
```

```
tileset.js:1259 Uncaught TypeError: Cannot read property '0' of undefined
    at Tileset.draw_type (tileset.js:1259)
    at Tileset.draw (tileset.js:893)
    at CanvasRenderer.draw (renderer-canvas.js:178)
    at Player._redraw (main.js:1153)
    at Player.redraw (main.js:1137)
```

**Comment by eevee** [comment] 2020-12-13 01:20
Augh, sorry, this was caused by a big messy change that turned out to be wrong anyway.  Should be fixed now.

**Closed by eevee** 2020-12-13 01:20 UTC
