### ISSUE TITLE
Visual lockup if heart or green heart inside glass block exists at any point

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#65] opened 2021-03-08 02:13 UTC

**Comment by Techokami** [comment] 2021-12-22 04:44
I believe this is a duplicate of solved issue #84 which was fixed in https://github.com/eevee/lexys-labyrinth/commit/073aba65ab83915b00a54dcc4e23ebe2c287361d

**Closed** 2021-12-22 23:48 UTC
