### ISSUE TITLE
Turning on debug mode before entering any level crashes

### ISSUE THREAD

**Issue by Patashu** [eevee/lexys-labyrinth#77] opened 2021-11-16 10:11 UTC
Nothing special required to reproduce it, happens every time

![image](https://user-images.githubusercontent.com/666597/141966053-6c35e4ce-c98f-4af8-a993-286efd007c8d.png)

**Comment by eevee** [comment] 2021-12-23 04:47
dupe of #53

**Closed by eevee** 2021-12-23 04:47 UTC
Labels: duplicate
